Bumps [actionview](https://github.com/rails/rails) from 7.2.1.2 to 7.2.2. <details> <summary>Release notes</summary> <p><em>Sourced from <a href="https://github.com/rails/rails/releases">actionview's releases</a>.</em></p> <blockquote> <h2>7.2.2</h2> <h2>Active Support</h2> <ul> <li> <p>Include options when instrumenting <code>ActiveSupport::Cache::Store#delete</code> and <code>ActiveSupport::Cache::Store#delete_multi</code>.</p> <p><em>Adam Renberg Tamm</em></p> </li> <li> <p>Print test names when running <code>rails test -v</code> for parallel tests.</p> <p><em>John Hawthorn</em>, <em>Abeid Ahmed</em></p> </li> </ul> <h2>Active Model</h2> <ul> <li> <p>Fix regression in <code>alias_attribute</code> to work with user defined methods.</p> <p><code>alias_attribute</code> would wrongly assume the attribute accessor was generated by Active Model.</p> <pre lang="ruby"><code>class Person   include ActiveModel::AttributeMethods <p>define_attribute_methods :name attr_accessor :name</p> <p>alias_attribute :full_name, :name end</p> <p>person.full_name # =&gt; NoMethodError: undefined method `attribute' for an instance of Person </code></pre></p> <p><em>Jean Boussier</em></p> </li> </ul> <h2>Active Record</h2> <ul> <li> <p>Fix support for <code>query_cache: false</code> in <code>database.yml</code>.</p> <p><code>query_cache: false</code> would no longer entirely disable the Active Record query cache.</p> <p><em>zzak</em></p> </li> <li> <p>Set <code>.attributes_for_inspect</code> to <code>:all</code> by default.</p> <p>For new applications it is set to <code>[:id]</code> in config/environment/production.rb.</p> <p>In the console all the attributes are always shown.</p> <p><em>Andrew Novoselac</em></p> </li> </ul> <!-- raw HTML omitted --> </blockquote> <p>... (truncated)</p> </details> <details> <summary>Changelog</summary> <p><em>Sourced from <a href="https://github.com/rails/rails/blob/v7.2.2/actionview/CHANGELOG.md">actionview's changelog</a>.</em></p> <blockquote> <h2>Rails 7.2.2 (October 30, 2024)</h2> <ul> <li>No changes.</li> </ul> </blockquote> </details> <details> <summary>Commits</summary> <ul> <li><a href="https://github.com/rails/rails/commit/d0dcb8fa6073a0c4d42600c15e82e3bb386b27d3"><code>d0dcb8f</code></a> Preparing for 7.2.2 release</li> <li><a href="https://github.com/rails/rails/commit/2975a880b6568207b2b3bbd8b6bf644e04b29bb5"><code>2975a88</code></a> Merge remote-tracking branch 'origin/7-2-sec' into 7-2-stable</li> <li><a href="https://github.com/rails/rails/commit/4c45fc1855630d095683d2e9effd7b7dd1d87983"><code>4c45fc1</code></a> Fix invalid syntax in TextHelper#highlight API docs example [ci skip]</li> <li><a href="https://github.com/rails/rails/commit/5f5349f1b2805a136a54be5c6db297c8afdbe893"><code>5f5349f</code></a> Merge remote-tracking branch 'origin/7-2-sec' into 7-2-stable</li> <li><a href="https://github.com/rails/rails/commit/c177aca25a3135201f4f8b88daeb47d4f968839d"><code>c177aca</code></a> Support Prism for ActionView::Template.spot</li> <li><a href="https://github.com/rails/rails/commit/c82f864659844f4d40c5462739f0da253f0b1635"><code>c82f864</code></a> Revert &quot;Skip Action View error mapping tests on 3.4+&quot;</li> <li><a href="https://github.com/rails/rails/commit/ef42ffc79f8b31cea6af4863fa82c9e67f87ac03"><code>ef42ffc</code></a> Skip Action View error mapping tests on 3.4+</li> <li><a href="https://github.com/rails/rails/commit/663754354ecaa5c65c7d76d0e0e5c8b4c4a0eaca"><code>6637543</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/53202">#53202</a> from byroot/ruby-3.4-hash-inspect</li> <li><a href="https://github.com/rails/rails/commit/080edd5ddd1a28ce73777078bc3369e8f434fc7d"><code>080edd5</code></a> Fix URI::DEFAULT_PARSER warnings</li> <li><a href="https://github.com/rails/rails/commit/5a735e9e05f8c045741b26b2ba74ed936ca04f73"><code>5a735e9</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/53049">#53049</a> from fatkodima/fix-link_to-with-symbol-rel</li> <li>See full diff in <a href="https://github.com/rails/rails/compare/v7.2.1.2...v7.2.2">compare view</a></li> </ul> </details> <br />
[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=actionview&package-manager=bundler&previous-version=7.2.1.2&new-version=7.2.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>