Bumps [rails](https://github.com/rails/rails) from 7.0.6 to 7.0.7. <details> <summary>Release notes</summary> <p><em>Sourced from <a href="https://github.com/rails/rails/releases">rails's releases</a>.</em></p> <blockquote> <h2>7.0.7</h2> <h2>Active Support</h2> <ul> <li> <p>Fix <code>Cache::NullStore</code> with local caching for repeated reads.</p> <p><em>fatkodima</em></p> </li> <li> <p>Fix <code>to_s</code> with no arguments not respecting custom <code>:default</code> formats</p> <p><em>Hartley McGuire</em></p> </li> <li> <p>Fix <code>ActiveSupport::Inflector.humanize(nil)</code> raising <code>NoMethodError: undefined method `end_with?' for nil:NilClass</code>.</p> <p><em>James Robinson</em></p> </li> <li> <p>Fix <code>Enumerable#sum</code> for <code>Enumerator#lazy</code>.</p> <p><em>fatkodima</em>, <em>Matthew Draper</em>, <em>Jonathan Hefner</em></p> </li> <li> <p>Improve error message when EventedFileUpdateChecker is used without a compatible version of the Listen gem</p> <p><em>Hartley McGuire</em></p> </li> </ul> <h2>Active Model</h2> <ul> <li> <p>Error.full_message now strips &quot;:base&quot; from the message.</p> <p><em>zzak</em></p> </li> <li> <p>Add a load hook for <code>ActiveModel::Model</code> (named <code>active_model</code>) to match the load hook for <code>ActiveRecord::Base</code> and allow for overriding aspects of the <code>ActiveModel::Model</code> class.</p> </li> </ul> <h2>Active Record</h2> <ul> <li> <p>Restores functionality to the missing method when using enums and fixes.</p> <p><em>paulreece</em></p> </li> <li> <p>Fix <code>StatementCache::Substitute</code> with serialized type.</p> <p><em>ywenc</em></p> </li> <li> <p>Fix <code>:db_runtime</code> on notification payload when application have multiple databases.</p> </li> </ul> <!-- raw HTML omitted --> </blockquote> <p>... (truncated)</p> </details> <details> <summary>Commits</summary> <ul> <li><a href="https://github.com/rails/rails/commit/522c86f35ccc80453ed9fb6ca8b394db321f9a69"><code>522c86f</code></a> Preparing for 7.0.7 release</li> <li><a href="https://github.com/rails/rails/commit/5610cbacc5630d775a1a7be78ccb17e561908cba"><code>5610cba</code></a> Sync CHANGELOG with the changes in the repository</li> <li><a href="https://github.com/rails/rails/commit/eb7e42d5ff7cab2544fdbc64761dcca0e12752e7"><code>eb7e42d</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/46617">#46617</a> from r7kamura/feature/isolation-level-default</li> <li><a href="https://github.com/rails/rails/commit/2dccb3f5ebebc42c917be537aebac47b9b6c5406"><code>2dccb3f</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/48891">#48891</a> from rails/rm-devcontainer-right</li> <li><a href="https://github.com/rails/rails/commit/fabd0b5827a3af1f189d726fbc7669f9fbdeef5e"><code>fabd0b5</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/48886">#48886</a> from fatkodima/backport-45670</li> <li><a href="https://github.com/rails/rails/commit/64ea100832b0a40eb8776e93cae6dd813fb5613d"><code>64ea100</code></a> Make sure nested base errors are translatable</li> <li><a href="https://github.com/rails/rails/commit/bc035fce6d82752322d391f0edfd98875530ad8d"><code>bc035fc</code></a> Use single quotes instead of double quotes to get SQLite constraints</li> <li><a href="https://github.com/rails/rails/commit/b9521b51f47c6739748259f8de43b170769c1bd8"><code>b9521b5</code></a> Remove duplicated fixture</li> <li><a href="https://github.com/rails/rails/commit/d25e34d19960f01118dc5d2ab78feea523d0be9f"><code>d25e34d</code></a> Fix <code>ActiveRecord::QueryMethods#in_order_of</code> to work with nils</li> <li><a href="https://github.com/rails/rails/commit/36597e2093add6457e213b3691746d1b27aaed07"><code>36597e2</code></a> Merge pull request <a href="https://redirect.github.com/rails/rails/issues/48861">#48861</a> from paulreece/correct_missing_and_associated_behavior</li> <li>Additional commits viewable in <a href="https://github.com/rails/rails/compare/v7.0.6...v7.0.7">compare view</a></li> </ul> </details> <br />
[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=rails&package-manager=bundler&previous-version=7.0.6&new-version=7.0.7)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>